default: &default
  adapter: postgresql
  database: ecommerce_dev
  username: postgres
  password: postgres
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
